version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bun-postgres
    restart: always
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: bun
      POSTGRES_PASSWORD: bun
      POSTGRES_DB: bun-database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
